name: "Java Release"
description: "Release a java version"

jobs:
  using: ubuntu-lastest 

  setup:
    steps:
      - uses: actions/checkout@v2

      - name: Remove SNAPSHOT from pom.xml  
        run:  sed -i 's/-SNAPSHOT//g' pom.xml

      - name: Setup Java 15
        uses: joschi/setup-jdk@v2   
          with:
          java-version: '15'

    build:
      steps:
        - name: Build the release jar
          run:  mvn package -Dmaven.test.skip=true

    release:
      steps:
        - name: Commit the released version
          run: |
            git config --local user.name  ${{ github.actor }}
            git add pom.xml
            VERSION=`sed -n '/version/,/version/p' pom.xml | head -1 | awk -F'[><]' '{print $3}'`
            git commit -am "Release version $VERSION - Updating the pom.xml"
            git push -f
            echo "v"$VERSION > version.txt

        - name: Create tag
          run: |
            ls
            cat version.txt | xargs git tag -a $1 -m "Version $1"
            git push --tags
    
  
